export const PendantPropList = [
  // {
  //   prop: 'username',
  //   label: '广告商名',
  //   columnWidth: '150',
  //   align: 'center',
  //   slotName: 'icon_class',
  // },
  {
    prop: 'title',
    label: '广告标题',
    columnWidth: '150',
    align: 'center',
    showOverflowTooltip: true,
    slotName: 'icon_class',
  },
  {
    prop: 'type',
    label: '广告类型',
    columnWidth: '100',
    align: 'center',
    slotName: 'type_class',
  },
  {
    prop: 'description',
    label: '文字描述',
    columnWidth: '200',
    align: 'center',
    showOverflowTooltip: true,
    slotName: 'description',
  },
  {
    prop: 'img_url',
    label: '广告图片',
    columnWidth: '160',
    align: 'center',
    slotName: 'img_url',
  },
  {
    prop: 'allowed_close',
    label: '支持关闭',
    columnWidth: '120',
    align: 'center',
    slotName: 'allowed_close',
    hasHeaderSlot: true,
  },
  {
    prop: 'web_path',
    label: '投放页面',
    columnWidth: '140',
    align: 'center',
    slotName: 'web_path',
  },
  {
    prop: 'is_show',
    label: '是否展示',
    columnWidth: '120',
    align: 'center',
    slotName: 'is_show',
  },
  {
    prop: 'position',
    label: '广告位置',
    columnWidth: '140',
    align: 'center',
    slotName: 'position',
  },
  {
    prop: 'start_ts',
    label: '开始时间',
    columnWidth: '180',
    align: 'center',
    slotName: 'start_ts',
  },
  {
    prop: 'end_ts',
    label: '结束时间',
    columnWidth: '180',
    align: 'center',
    slotName: 'end_ts',
  },
  {
    prop: 'url',
    label: '跳转地址',
    columnWidth: '300',
    align: 'center',
    slotName: 'url',
    showOverflowTooltip: true,
  },
]
